/*
 * tracfficlight.c
 *
 *  Created on: Nov 6, 2023
 *      Author: haoha
 */


#include "trafficlight.h"

void traffic_light(int status){
	switch(status){

	case INIT:
	HAL_GPIO_WritePin(RED1_GPIO_Port, RED1_Pin,RESET);
	HAL_GPIO_WritePin(GREEN1_GPIO_Port, GREEN1_Pin,RESET);
	HAL_GPIO_WritePin(YELLOW1_GPIO_Port, YELLOW1_Pin,RESET);
	HAL_GPIO_WritePin(RED2_GPIO_Port, RED2_Pin,RESET);
	HAL_GPIO_WritePin(GREEN2_GPIO_Port, GREEN2_Pin,RESET);
	HAL_GPIO_WritePin(YELLOW2_GPIO_Port, YELLOW2_Pin,RESET);
	break;

	case RED1_GREEN:
	HAL_GPIO_WritePin(RED1_GPIO_Port, RED1_Pin,SET);
	HAL_GPIO_WritePin(GREEN1_GPIO_Port, GREEN1_Pin,RESET);
	HAL_GPIO_WritePin(YELLOW1_GPIO_Port, YELLOW1_Pin,RESET);
	HAL_GPIO_WritePin(RED2_GPIO_Port, RED2_Pin,RESET);
	HAL_GPIO_WritePin(GREEN2_GPIO_Port, GREEN2_Pin,SET);
	HAL_GPIO_WritePin(YELLOW2_GPIO_Port, YELLOW2_Pin,RESET);
    break ;

	case RED1_YELLOW :
		HAL_GPIO_WritePin(RED1_GPIO_Port, RED1_Pin,SET);
		HAL_GPIO_WritePin(GREEN1_GPIO_Port, GREEN1_Pin,RESET);
		HAL_GPIO_WritePin(YELLOW1_GPIO_Port, YELLOW1_Pin,RESET);
		HAL_GPIO_WritePin(RED2_GPIO_Port, RED2_Pin,RESET);
		HAL_GPIO_WritePin(GREEN2_GPIO_Port, GREEN2_Pin,RESET);
		HAL_GPIO_WritePin(YELLOW2_GPIO_Port, YELLOW2_Pin,SET);
		break;

	case GREEN1_RED :
		HAL_GPIO_WritePin(RED1_GPIO_Port, RED1_Pin,RESET);
		HAL_GPIO_WritePin(GREEN1_GPIO_Port, GREEN1_Pin,SET);
		HAL_GPIO_WritePin(YELLOW1_GPIO_Port, YELLOW1_Pin,RESET);
		HAL_GPIO_WritePin(RED2_GPIO_Port, RED2_Pin,SET);
		HAL_GPIO_WritePin(GREEN2_GPIO_Port, GREEN2_Pin,RESET);
		HAL_GPIO_WritePin(YELLOW2_GPIO_Port, YELLOW2_Pin,RESET);
		break;

	case YELLOW1_RED :
		HAL_GPIO_WritePin(RED1_GPIO_Port, RED1_Pin,RESET);
		HAL_GPIO_WritePin(GREEN1_GPIO_Port, GREEN1_Pin,RESET);
		HAL_GPIO_WritePin(YELLOW1_GPIO_Port, YELLOW1_Pin,SET);
		HAL_GPIO_WritePin(RED2_GPIO_Port, RED2_Pin,SET);
		HAL_GPIO_WritePin(GREEN2_GPIO_Port, GREEN2_Pin,RESET);
		HAL_GPIO_WritePin(YELLOW2_GPIO_Port, YELLOW2_Pin,RESET);
		break;
	case RED:
		HAL_GPIO_TogglePin(RED1_GPIO_Port, RED1_Pin);
		HAL_GPIO_WritePin(GREEN1_GPIO_Port, GREEN1_Pin,RESET);
		HAL_GPIO_WritePin(YELLOW1_GPIO_Port, YELLOW1_Pin,RESET);
		HAL_GPIO_TogglePin(RED2_GPIO_Port, RED2_Pin);
		HAL_GPIO_WritePin(GREEN2_GPIO_Port, GREEN2_Pin,RESET);
		HAL_GPIO_WritePin(YELLOW2_GPIO_Port, YELLOW2_Pin,RESET);
		break;
	case GREEN:
		HAL_GPIO_WritePin(RED1_GPIO_Port, RED1_Pin,RESET);
		HAL_GPIO_TogglePin(GREEN1_GPIO_Port, GREEN1_Pin);
		HAL_GPIO_WritePin(YELLOW1_GPIO_Port, YELLOW1_Pin,RESET);
		HAL_GPIO_WritePin(RED2_GPIO_Port, RED2_Pin,RESET);
		HAL_GPIO_TogglePin(GREEN2_GPIO_Port, GREEN2_Pin);
		HAL_GPIO_WritePin(YELLOW2_GPIO_Port, YELLOW2_Pin,RESET);
		break;
	case YELLOW:
		HAL_GPIO_WritePin(RED1_GPIO_Port, RED1_Pin,RESET);
		HAL_GPIO_WritePin(GREEN1_GPIO_Port, GREEN1_Pin,RESET);
		HAL_GPIO_TogglePin(YELLOW1_GPIO_Port, YELLOW1_Pin);
		HAL_GPIO_WritePin(RED2_GPIO_Port, RED2_Pin,RESET);
		HAL_GPIO_WritePin(GREEN2_GPIO_Port, GREEN2_Pin,RESET);
		HAL_GPIO_TogglePin(YELLOW2_GPIO_Port, YELLOW2_Pin);
		break;
    default:
	break;
	}
}

